# Generated by Django 4.0.1 on 2022-04-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(default='1 kg', max_length=10)),
                ('availability', models.CharField(default='available', max_length=12)),
                ('quantity', models.IntegerField()),
                ('description_short', models.CharField(default='available', max_length=64)),
                ('description_long', models.TextField(default='available')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notice', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
                ('mobile', models.CharField(blank=True, max_length=16)),
                ('shipping_address', models.TextField(blank=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ordered_time', models.DateTimeField(auto_now_add=True)),
                ('expected_time_request', models.TextField(blank=True)),
                ('delivery_time', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(default='Pending', max_length=32)),
                ('ordered_items', models.ManyToManyField(blank=True, related_name='items', to='shop.Ordered_item')),
            ],
        ),
    ]
