# Generated by Django 4.0.1 on 2022-03-22 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('KILIKIA CELEBRATORY', 'KILIKIA CELEBRATORY'), ('KILIKIA JUBILEE', 'KILIKIA JUBILEE'), ('KILIKIA ELITAR', 'KILIKIA ELITAR'), ('KILIKIA DARK', 'KILIKIA DARK'), ('ZHIGULYOVSKOE ', 'ZHIGULYOVSKOE '), ('1952', '1952')], default='KILIKIA CELEBRATORY', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit', models.CharField(default='1 ly', max_length=10)),
                ('availability', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable'), ('coming soon', 'coming soon')], default='available', max_length=32)),
                ('quantity', models.IntegerField()),
                ('description_short', models.CharField(default='available', max_length=64)),
                ('description_long', models.TextField(default='available')),
                ('image', models.ImageField(blank=True, default=None, upload_to='static/images', verbose_name='Product Image')),
                ('image_filename', models.CharField(default='image.png', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Ordered_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notice', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='ecom.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32)),
                ('mobile', models.CharField(blank=True, max_length=16)),
                ('shipping_address', models.TextField(blank=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ordered_time', models.DateTimeField(auto_now_add=True)),
                ('expected_time_request', models.TextField(blank=True)),
                ('delivery_time', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Prepared', 'Prepared'), ('Shipping', 'Shipping'), ('Delivered', 'Delivered')], default='Pending', max_length=32)),
                ('ordered_items', models.ManyToManyField(blank=True, related_name='items', to='ecom.Ordered_item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
